spring:
  profiles:
    active: local
  application:
    name: gyugyufelt
  datasource:
    url: jdbc:postgresql://localhost:5432/woolfelt_db
#    url: jdbc:mariadb://localhost:3306/woolfelt_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false          # 영속성 컨텍스트를 뷰까지 열어둘 필요 없으면 false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha    # API 그룹 알파벳 순 정렬
    operationSorter: method # HTTP Method 순 정렬 (G -> Po -> Pu ->  D)
