services:
  db:
    image: postgres:16
    restart: unless-stopped # 컨테이너가 죽어도 자동 재시작, 서버 재부팅시 자동 기동
    environment:
      POSTGRES_USER: wooluser # TODO: Change
      POSTGRES_PASSWORD: woolpass123 # TODO: Change
      POSTGRES_DB: woolfelt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # DB 파일 디렉터리를 호스트 볼륨에 매핑
volumes:
  pgdata:
