services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: woolfelt_db
      MARIADB_USER: wooluser
      MARIADB_PASSWORD: woolpass123
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
