spring:
  profiles:
    active: local
  application:
    name: gyugyufelt
  datasource:
    url: jdbc:mariadb://localhost:3306/woolfelt_db
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

