spring:
  profiles:
    active: local
  application:
    name: gyugyufelt
  datasource:
    url: jdbc:postgresql://localhost:5432/woolfelt_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha    # API 그룹 알파벳 순 정렬
    operationSorter: method # HTTP Method 순 정렬 (G -> Po -> Pu ->  D)
